### ISSUE TITLE
When a iam role authenticates with an invalid region, a 500 is returned instead of a 400

### ISSUE THREAD

**Issue by fieldju** [Nike-Inc/cerberus-management-service#18]
```
traceId=e7e8ba519c741e85 2017-02-04T05:08:44,955Z [epollEventLoopGroup-3-7] appname=cms environment=cerberus-test version=0.12.0 |-ERROR c.n.b.h.r.RiposteUnhandledExceptionHandler - Caught unhandled exception: error_uid=e3dc74a9-afba-48f4-a1e9-2494e23b89e5, dtrace_id=e7e8ba519c741e85, exception_class=java.util.concurrent.CompletionException, returned_http_status_code=500, contributing_errors="GENERIC_SERVICE_ERROR", request_uri="/v1/auth/iam-role", request_method="POST", query_string="null", request_headers="Accept=application/json,CloudFront-Viewer-Country=US,CloudFront-Forwarded-Proto=https,CloudFront-Is-Tablet-Viewer=false,CloudFront-Is-Mobile-Viewer=false,X-Forwarded-Proto=https,Connection=keep-alive,CloudFront-Is-SmartTV-Viewer=false,X-Forwarded-Port=443,Via=1.1 a970721b7e7e7717531fc56b64b3884f.cloudfront.net (CloudFront),host=xxxxxxxxxxxxxx,X-Amz-Cf-Id=VPUCT40x9KqdIQV4fwZN4Pjv1oYYYER4RrIqh6jjyJFBFlIAiVGtLg==,X-Forwarded-For=52.55.130.29, 54.239.145.100, 172.20.0.252, 172.20.8.39,content-type=application/json,Content-Length=88,X-Real-IP=172.20.0.252,CloudFront-Is-Desktop-Viewer=true", unhandled_error="true"
java.util.concurrent.CompletionException: java.lang.IllegalArgumentException: Specified region is not valid.
	at java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:273)
	at java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:280)
	at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1592)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.IllegalArgumentException: Specified region is not valid.
	at com.nike.cerberus.aws.KmsClientFactory.getClient(KmsClientFactory.java:65)
	at com.nike.cerberus.service.KmsService.provisionKmsKey(KmsService.java:79)
	at org.mybatis.guice.transactional.TransactionalMethodInterceptor.invoke(TransactionalMethodInterceptor.java:102)
	at com.nike.cerberus.service.AuthenticationService.getKeyId(AuthenticationService.java:363)
	at com.nike.cerberus.service.AuthenticationService.authenticate(AuthenticationService.java:179)
	at com.nike.cerberus.endpoints.authentication.AuthenticateIamRole.lambda$execute$13(AuthenticateIamRole.java:51)
	at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1590)
	... 3 common frames omitted
Caused by: java.lang.IllegalArgumentException: Cannot create enum from us-east-2 value!
	at com.amazonaws.regions.Regions.fromName(Regions.java:73)
	at com.nike.cerberus.aws.KmsClientFactory.getClient(KmsClientFactory.java:62)
	... 9 common frames omitted
```

Need to handle this exception, as it is leaking as a generic server error.

**Comment by sdford** [comment]
Fixed by PR #37
