### ISSUE TITLE
Regex Parsing Bug on IAM Role Authentication

### ISSUE THREAD

**Issue by dylan-raithel-lookout** [Nike-Inc/cerberus-management-service#183]
For an IAM role that exists, and is attached to an SDB, Cerberus throws an authentication error. It looks like a parsing bug on the role name that leads to the name being suffixed with a space. When I remove and re-add the role from the SDB, save it, then edit it, I can confirm that it's adding another space.

Initial stack trace:

A Important error occured
com.amazonaws.services.kms.model.AWSKMSException: Unable to authenticate <role name with an extra trailing space> IAM role due to the following error(s):
Error ID:64081477-2add-4ccf-a042-d6627076474f
Code: 10
Message: An error occurred while fulfilling the request
Please refer to the Cerberus Java Client documentation.
If you are unsure of what this means please ask in the #cd channel on Slack. (Service: null; Status Code: 0; Error Code: null; Request ID: null)
	at com.lookout.cerberus.client.SecretStoreClient.authenticate(SecretStoreClient.java:110)
	at com.lookout.cerberus.client.SecretStoreClient.<init>(SecretStoreClient.java:50)
	at com.lookout.cerberus.client.SecretStoreClient.<init>(SecretStoreClient.java:58)
	at com.lookout.cerberus.client.Cerberus.initializeCerberusClient(Cerberus.java:82)
	at com.lookout.cerberus.client.Cerberus.fetchFromCerberus(Cerberus.java:59)
	at com.lookout.cerberus.client.Cerberus.retrieve(Cerberus.java:53)
	at com.lookout.bac.instruction.processor.FileSystemSecretSaver.process(FileSystemSecretSaver.java:30)
	at com.lookout.bac.instruction.processor.InstructionProcessor.processInstruction(InstructionProcessor.java:13)
	at com.lookout.bac.instruction.InstructionManager.process(InstructionManager.java:33)
	at com.lookout.bac.instruction.InstructionManager.processInstruction(InstructionManager.java:38)
	at com.lookout.bac.Application.main(Application.java:30)

See attached screenshots as well.

**Comment by fieldju** [comment]
@dylan-raithel-lookout we will check this out.
